name: CI

on:
  push:
    branches:
      - '**'

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [12, 14, 16, 18]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - run: npm ci

      - run: npm t

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm ci

      - run: npm run lint:strict
